export const collegeData = [
  {
    id: 1,
    imgUrl: "https://picsum.photos/300/150",
    name: "BRAC University",
    admissionDate: "15/12/2023",
    events: "hackathons.",
    research: "3 Paper",
    sports: "Lorem, ipsum.",
    slug: "brac-university",
  },
  {
    id: 2,
    imgUrl: "https://picsum.photos/300/150",
    name: "Harvard University",
    admissionDate: "20/08/2024",
    events: "Conferences, seminars.",
    research: "10 Papers",
    sports: "Football, basketball.",
    slug: "harvard-university",
  },
  {
    id: 3,
    imgUrl: "https://picsum.photos/300/150",
    name: "Stanford University",
    admissionDate: "10/05/2024",
    events: "Workshops, hackathons.",
    research: "5 Papers",
    sports: "Tennis, swimming.",
    slug: "stanford-university",
  },
  {
    id: 4,
    imgUrl: "https://picsum.photos/300/150",
    name: "Massachusetts Institute of Technology",
    admissionDate: "01/09/2024",
    events: "Tech symposiums, coding competitions.",
    research: "8 Papers",
    sports: "Soccer, track and field.",
    slug: "massachusetts-institute-of-technology",
  },
  {
    id: 5,
    imgUrl: "https://picsum.photos/300/150",
    name: "University of Oxford",
    admissionDate: "12/10/2024",
    events: "Debates, literary festivals.",
    research: "7 Papers",
    sports: "Rowing, cricket.",
    slug: "university-of-oxford",
  },
  {
    id: 6,
    imgUrl: "https://picsum.photos/300/150",
    name: "Yale University",
    admissionDate: "05/07/2024",
    events: "Art exhibitions, cultural festivals.",
    research: "6 Papers",
    sports: "Squash, rugby.",
    slug: "yale-university",
  },
  {
    id: 7,
    imgUrl: "https://picsum.photos/300/150",
    name: "University of Cambridge",
    admissionDate: "18/03/2024",
    events: "Science fairs, astronomy clubs.",
    research: "9 Papers",
    sports: "Polo, archery.",
    slug: "university-of-cambridge",
  },
  {
    id: 8,
    imgUrl: "https://picsum.photos/300/150",
    name: "Princeton University",
    admissionDate: "30/11/2024",
    events: "Mathematics contests, research forums.",
    research: "4 Papers",
    sports: "Fencing, lacrosse.",
    slug: "princeton-university",
  },
];
